import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Display from "@/components/Display/Display";
import Buttons from "@/components/Buttons/Buttons";
import { useState } from "react";
import { Operator, Equal } from "@/types";

export default function Home() {
  const [value1, setValue1] = useState("");
  const [value2, setValue2] = useState("");
  const [operator, setOperator] = useState<Operator | "">("");

  console.log("value1", value1);
  console.log("operator", operator);
  console.log("value2", value2);

  const handleNumClick = (value: string) => {
    if (operator) {
      setValue2((prevValue2) => `${prevValue2}${value}`);
      return;
    }
    setValue1((prevValue1) => `${prevValue1}${value}`);
  };

  const handleOperatorClick = (operator: Operator | Equal) => {
    if (operator === "=") {
      return;
    }
    setOperator(operator);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Display value="-4" />
        <Buttons
          handleNumClick={handleNumClick}
          handleOperatorClick={handleOperatorClick}
        />
      </main>
    </>
  );
}
