import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Display from "@/components/Display/Display";
import Buttons from "@/components/Buttons/Buttons";
import { useState } from "react";
import { Operator, Equal } from "@/types";

export default function Home() {
  const [storage, setStorage] = useState(0);
  const [display, setDisplay] = useState("");
  const [operator, setOperator] = useState<Operator | "">("");

  const handleNumClick = (value: string) => {
    setDisplay((prevValue) => `${prevValue}${value}`);
  };

  const handleOperatorClick = (newOperator: Operator | Equal) => {
    switch (newOperator) {
      case "+":
      case "-":
      case "*":
      case "/":
        setStorage((prevStorage) => {
          if (operator) {
            let result = 0;
            switch (operator) {
              case "+":
                result = prevStorage + Number(display);
                break;
              case "-":
                result = prevStorage - Number(display);
                break;
              case "*":
                result = prevStorage * Number(display);
                break;
              case "/":
                result = prevStorage / Number(display);
                break;
            }
            return result;
          }

          return prevStorage;
        });
        setOperator(newOperator);
        setDisplay("");
        break;
      case "=":
        setDisplay((prevDisplay) => {
          if (operator) {
            let result = 0;
            switch (operator) {
              case "+":
                result = storage + Number(prevDisplay);
                break;
              case "-":
                result = storage - Number(prevDisplay);
                break;
              case "*":
                result = storage * Number(prevDisplay);
                break;
              case "/":
                result = storage / Number(prevDisplay);
                break;
            }
            return result.toString();
          }

          return prevDisplay;
        });
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Display value={display} />
        <Buttons
          handleNumClick={handleNumClick}
          handleOperatorClick={handleOperatorClick}
        />
      </main>
    </>
  );
}
