import { useCallback, useState } from "react";
import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Search from "@/components/Search";
import List from "@/components/List";
import data from "@/data/";

const allEpisodes = data.episodes;

export default function Home() {
  const [episodes, setEpisodes] = useState(allEpisodes);

  const handleFilter = useCallback((search: string) => {
    setEpisodes(
      allEpisodes.filter((episode) =>
        episode.title.toLowerCase().includes(search.toLowerCase())
      )
    );
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Search onFilter={handleFilter} />
        <List episodes={episodes} />
      </main>
    </>
  );
}
