import { useState } from "react";
import Head from "next/head";
import styles from "@/styles/Home.module.css";

export default function Home() {
  const [number, setNumber] = useState(0);

  return (
    <>
      <Head>
        <title>First React App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <span className={styles.number}>{number}</span>
        <button
          className={styles.button}
          onClick={() => {
            setNumber((prevNumber) => prevNumber + 1);
          }}
        >
          +
        </button>
        <button
          className={styles.button}
          onClick={() => {
            setNumber((prevNumber) => prevNumber - 1);
          }}
        >
          -
        </button>
      </main>
    </>
  );
}
